### ISSUE TITLE
'Eject' command is vanilla

### ISSUE THREAD

**Issue by MiniSvamp** [Sehelitar/IQuit#1]
Your mod reimplements the already existing terminal command, "eject". The only difference I can see at a quick glance is that your mod _seems_ to allow quitting out whilst not in orbit.

**Comment by Sehelitar** [comment]
Hey! 👋
You're right, it's very similar but with some differences:
* ``eject`` command is hidden, mine is not. I asked a few players I know if they knew about that ``eject`` command, most didn't.
* I had cases with mods where the ``eject`` command would actually be broken and wouldn't work. Mine doesn't seem to be affected, but I don't know exactly why though.
* You can change the configuration to make my command available to everyone. ``eject`` can only be run by the host.

So yeah, this is not a "must-have" mod but more a marginal quality-of-life mod for the small amount of people that reset their game often and early, and have problems with the native command.

**Comment by Sehelitar** [comment]
The mod has been updated and now it can actually skip the long eject sequence and reset the game instantly. It also works when the ship has landed (kinda). 🥳
